- hosts: localhost
  become: true
  tasks: 
    # Package
    - name: Install packages
      apt: name={{item}}
      with_items:
        - htop
        - curl
        - wget
        - unzip
        - fontconfig
        # alacritty dependency
        - cmake 
        - g++ 
        - pkg-config 
        - libfreetype6-dev 
        - libfontconfig1-dev 
        - libxcb-xfixes0-dev 
        - libxkbcommon-dev
        - python3
        - stow
        # zsh
        - zsh
        - fzf

    # Dotfile
    - name: Clone dotfile directory 
      ansible.builtin.git:
        repo: "https://github.com/CookieGigi/dotfile.git"
        dest: $HOME/dotfile
    - name: Stow dotfile
      ansible.builtin.command: stow -d $HOME/dotfile/ .

    # Cargo
    - name: check if cargo is installed
      shell: command -v cargo
      register: cargo_exists
      ignore_errors: yes
    - name: Download Installer
      when: cargo_exists is failed
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
        force: 'yes'
      tags:
        - rust
    - name: install rust/cargo
      when: cargo_exists is failed
      shell: /tmp/sh.rustup.rs -y
      tags:
        - rust

    # Cargo packages
    - name: Cargo packages
      community.general.cargo:
        executable: ~/.cargo/bin/cargo
        name:
          - alacritty
    # Oh my zsh
    - name: Clone oh my zsh
      ansible.builtin.git:
        repo: "https://github.com/ohmyzsh/ohmyzsh.git"
        dest: $HOME/.oh-my-zsh
    - name: Set default shell
      ansible.builtin.command: chsh -s /usr/bin/zsh

    # ZSH Plugin
    - name: Install ZSH plugin
      ansible.builtin.git:
        repo: "{{item.url}}"
        dest: $HOME/.oh-my-zsh/plugins/{{item.name}}
      with_items:
        - name: zsh-syntax-highlighting
          url: https://github.com/zsh-users/zsh-syntax-highlighting.git
        - name: zsh-autosuggestions
          url: https://github.com/zsh-users/zsh-autosuggestions.git


    # Nerd font
    - name: Create dir
      command: mkdir -p $HOME/.local/share/fonts/
    - name: Install NerdFont
      include_tasks: font.yaml 
      with_items:
        - JetBrainsMono
    - name: Refresh Font Cache 
      command: fc-cache -fv

