- hosts: localhost
  tasks: 
    # Package
    - name: Install packages
      become: true
      apt: name={{item}}
    # Install local script
    - name: Install eza
      script: "{{item}}"
      with_items:
        - htop
        - curl
        - wget
        - unzip
        - fontconfig
        # alacritty dependency
        - cmake 
        - g++ 
        - pkg-config 
        - libfreetype6-dev 
        - libfontconfig1-dev 
        - libxcb-xfixes0-dev 
        - libxkbcommon-dev
        - python3
        - stow
        # zsh
        - zsh
        - fzf
        # tmux
        - tmux
        - "./eza_install.sh"

    # Dotfile
    - name: Clone dotfile directory 
      ansible.builtin.git:
        repo: "https://github.com/CookieGigi/dotfile.git"
        dest: $HOME/dotfile
    - name: Stow dotfile
      ansible.builtin.command: stow -d $HOME/dotfile/ .
    
    # Install from script
    - name: Install from script
      include_tasks: install_sh.yaml
      with_items:
        - name: cargo
          url: https://sh.rustup.rs 
          arg: -y
          pathcommand: $HOME/.cargo/bin/cargo
        
    # Cargo packages
    - name: Cargo packages
      community.general.cargo:
        executable: ~/.cargo/bin/cargo
        name:
          - alacritty
          - zoxide
        locked: true
    
    # Oh my zsh
    - name: Clone oh my zsh
      ansible.builtin.git:
        repo: "https://github.com/ohmyzsh/ohmyzsh.git"
        dest: $HOME/.oh-my-zsh
    - name: Set default shell
      become: true
      ansible.builtin.command: chsh -s /usr/bin/zsh

    # ZSH Plugin
    - name: Install ZSH plugin
      ansible.builtin.git:
        repo: "{{item.url}}"
        dest: $HOME/.oh-my-zsh/plugins/{{item.name}}
      with_items:
        - name: zsh-syntax-highlighting
          url: https://github.com/zsh-users/zsh-syntax-highlighting.git
        - name: zsh-autosuggestions
          url: https://github.com/zsh-users/zsh-autosuggestions.git


    # Nerd font
    - name: Create dir
      command: mkdir -p $HOME/.local/share/fonts/
    - name: Install NerdFont
      include_tasks: font.yaml 
      with_items:
        - JetBrainsMono
    - name: Refresh Font Cache 
      command: fc-cache -fv
    # Gnome
    - name: Setup gnome
      include_tasks: gnome.yaml
      tags:
        - gnome

