- hosts: localhost
  tasks: 
    # Repository
    # - name: Add Repositries
    #   apt_repository:
    #     repo: "{{item}}"
    #   with_items:
    # Update & upgrade
    - name: Update
      become: true
      apt:
        update-cache: yes
      ignore_errors: yes
    - name: Upgrade
      become: true
      apt:
        upgrade: dist

    # Package
    - name: Install packages
      become: true
      apt: 
        name: 
          - htop
          - curl
          - wget
          - unzip
          - fontconfig
          - gpg
          - software-properties-common
          - build-essential
          - libreadline-dev 
          - libssl-dev
          - ripgrep
          - tar
          - xclip
          - rclone
          # alacritty
          - cmake 
          - g++ 
          - pkg-config 
          - libfreetype6-dev 
          - libfontconfig1-dev 
          - libxcb-xfixes0-dev 
          - libxkbcommon-dev
          - python3
          - stow
          - alacritty 
          # zsh
          - zsh
          - fzf
          # tmux
          - tmux
          # neovim
          - luarocks
          - fd-find
          # dotnet
          - dotnet-sdk-8.0
          # tlp
          - tlp
          - tlp-rdw
          # gnome
          - gnome-shell-extensions
          - gnome-shell-extension-manager
          # flatpak
          - flatpak
          - gnome-software-plugin-flatpak
          # android debug
          - adb

    # Snap
    - name: Install Snap Classic Package
      become: true
      community.general.snap:
        classic: true
        name:
          - obsidian
          - nvim 
          - codium
    - name: Install Snap package
      become: true
      community.general.snap:
        name:
          - steam

    # Install local script
    - name: Install eza
      script: "{{item}}"
      with_items:
        - "./lazygit_install.sh"
        - "./eza_install.sh"
        - "./node_install.sh"



    # Install from remote script
    - name: Install from remote script
      include_tasks: install_sh.yaml 
      with_items:
        - name: zoxide
          url: https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh 
          pathcommand: zoxide
          arg: ""
        - name: tailscale
          url: https://tailscale.com/install.sh
          pathcommand: tailscale
          arg: ""
      
    # Dotfile
    - name: Clone dotfile directory 
      ansible.builtin.git:
        repo: "git@github.com:CookieGigi/dotfile.git"
        dest: $HOME/dotfile
    - name: Stow dotfile
      ansible.builtin.command: stow -d $HOME/dotfile/ .
        
    # Cargo packages
    - name: Cargo packages
      community.general.cargo:
        executable: ~/.cargo/bin/cargo
        name:
          - alacritty
          - zoxide
          - tree-sitter-cli
          - htmx-lsp
        locked: true

    # npm package
    - name: Install node.js package globally.
      community.general.npm:
        name: "{{item}}" 
        global: true
      with_items:
        - vscode-langservers-extracted 
        - dockerfile-language-server-nodejs
        - typescript
        - typescript-language-server
        - "@tailwindcss/language-server"

        
    # Dotnet package
    - name: Dotnet Package
      command: "dotnet tool install --global {{item}}"
      ignore_errors: yes
      with_items:
        - csharp-ls
    # Pip package
    - name: Install pipx package
      command : pipx install {{item}}
      with_items: 
        - python-lsp-server 
        - gnome-extensions
      ignore_errors: yes
    # Oh my zsh
    - name: Clone oh my zsh
      ansible.builtin.git:
        repo: "https://github.com/ohmyzsh/ohmyzsh.git"
        dest: $HOME/.oh-my-zsh
    - name: Set default shell
      become: true
      ansible.builtin.command: chsh -s /usr/bin/zsh

    # ZSH Plugin
    - name: Install ZSH plugin
      ansible.builtin.git:
        repo: "{{item.url}}"
        dest: $HOME/.oh-my-zsh/plugins/{{item.name}}
      with_items:
        - name: zsh-syntax-highlighting
          url: https://github.com/zsh-users/zsh-syntax-highlighting.git
        - name: zsh-autosuggestions
          url: https://github.com/zsh-users/zsh-autosuggestions.git


    # Nerd font
    - name: Create dir
      command: mkdir -p $HOME/.local/share/fonts/
    - name: Install NerdFont
      include_tasks: font.yaml 
      with_items:
        - JetBrainsMono
    - name: Refresh Font Cache 
      command: fc-cache -fv
    #Tmux plugin manager
    - name: Install tmux plugin manager
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm
    - name: Tmux catpuccin
      ansible.builtin.git:
        repo: https://github.com/catppuccin/tmux.git
        dest: ~/.config/tmux/plugins/catppuccin/tmux
        version: v2.1.2

    # Neovim
    - name: JSRegexp for luasnip
      become: true
      command: sudo luarocks install jsregexp

    # Gnome
    - name: Setup gnome
      include_tasks: gnome.yaml
      tags:
        - gnome

