- hosts: localhost
  tasks:
    - name : Package
      become: true
      apt:
        name:
          - openjdk-11-jdk
          # Hardware acceleration
          - qemu-kvm 
          - libvirt-daemon-system 
          - libvirt-clients
          - bridge-utils
 
