- name: "Install ripgrep"
  become: true
  apt:
    name: "ripgrep"
- name: "Install fzf"
  become: true
  apt:
    name: "fzf"
- name: "Install fd-find"
  become: true
  apt:
    name: "fd-find"

- name: Install eza
  become: true
  script: 
    cmd: "./eza_install.sh" 
    creates: /usr/bin/eza

- name: Install zoxide
  include_role: 
    name: install_from_remote_script 
  vars:
    name: zoxide
    url: https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh 
    pathcommand: zoxide
    arg: ""
- name: Install cpc
  community.general.cargo:
    name: cpc
    locked: true
