- name: "Add repository"
  become: true
  ansible.builtin.apt_repository:
    repo: 'ppa:mbudde/ledger'
    state: present
    codename: trusty
- name: "Update apt cache"
  include_role:
    name: "apt-update-cache"
- name: "Install ledger"
  become: true
  apt:
    name: ledger

