- name: "Install alacritty and dependencies"
  become: true
  apt:
    name:
      - cmake 
      - g++ 
      - pkg-config 
      - libfreetype6-dev 
      - libfontconfig1-dev 
      - libxcb-xfixes0-dev 
      - libxkbcommon-dev
      - python3
      - alacritty
