argument_specs:
  main:
    short_description: Install from a remote script 
    description:
      - Install from a remote script
    author:
      - Cookiegigi 
    options:
      pathcommand:
        type: "path"
        required: true
      url:
        type: "str"
        required: "true"
      name:
        type: "str"
        required: "true"
      arg:
        type: "str"
        default: ""
